apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  containers:
  - name: volume-container-xfusion-1
    image: debian:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/ecommerce
  - name: volume-container-xfusion-2
    image: debian:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps

  volumes:
  - name: volume-share
    emptyDir: {}
