apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-app
    type: redis-slave
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: redis-app
    type: redis-slave
