apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-app
    type: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
      type: redis-master
  template:
    metadata:
      labels:
        app: redis-app
        type: redis-master
    spec:
      containers:
      - name:  master-redis-devops
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
