---
- name: Deploy playbook
  hosts: all
  serial: 1
  any_errors_fatal: true
  gather_facts: true
  become: true
  tasks:
    - name: unarchive the zip on app servers
      unarchive:
        src: /usr/src/data/xfusion.zip
        dest: /opt/data/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0777'
