apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
data:
  password: WVVJaWRoYjY2Nw==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
data:
  username: a29kZWtsb3VkX3RpbQ==
  password: TFFmS2VXV3hXRA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
data:
  database: a29kZWtsb3VkX2RiNg==