apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-devops
spec:
  template:
    metadata:
      name: countdown-devops
    spec:
      containers:
      - name: container-countdown-devops
        image: centos:latest
        command: ["/bin/bash"]
        args: ["-c","for i in ten nine eight seven six five four three two one ; do echo $i ; done"]
      restartPolicy: Never
  backoffLimit: 4
