apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-datacenter
  namespace: httpd-namespace-datacenter
  labels:
    app: httpd_app_datacenter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_datacenter
  template:
    metadata:
      labels:
        app: httpd_app_datacenter
    spec:
      containers:
      - name: httpd-container-datacenter
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  namespace: httpd-namespace-datacenter
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    app: httpd_app_datacenter
