---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-nautilus
  namespace: node-namespace-nautilus
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container-nautilus
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  node-service-nautilus
  namespace: node-namespace-nautilus
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30012
  selector:
    app: node
