#### Init Containers in Kubernetes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-xfusion
  labels:
    app: ic-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-xfusion
  template:
    metadata:
      labels:
        app: ic-xfusion
    spec:
      containers:
      - name: ic-main-xfusion
        image: fedora:latest
        command: ["/bin/bash"]
        args: ["-c", "while true; do cat /ic/ecommerce; sleep 5; done"]
        volumeMounts:
          - name: ic-volume-xfusion
            mountPath: /ic
      initContainers:
      - name: ic-msg-xfusion
        image: fedora:latest
        command: [ "/bin/bash" ]
        args: ["-c", "echo Init Done - Welcome to xFusionCorp Industries > /ic/ecommerce"]
        volumeMounts:
          - name: ic-volume-xfusion
            mountPath: /ic
      volumes:
      - name: ic-volume-xfusion
        emptyDir: {}
