apiVersion: v1
kind: Pod
metadata:
   name: httpd-pod
spec:
  containers:
  - image: httpd:latest
    name: httpd-container
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "15Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "100m"