apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
spec:
  volumes:
    - name: storage-nautilus
      persistentVolumeClaim:
        claimName: pvc-nautilus
  containers:
    - image: nginx:latest
      name: container-nautilus
      ports:
        - containerPort: 80
          name: "web"
      volumeMounts:
        - mountPath: /usr/share/nginx/html"
          name: storage-nautilus
