apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
    app: web
spec:
  containers:
    - name: container-datacenter
      image: httpd:latest
      volumeMounts:
      - mountPath: "/usr/share/nginx/www"
        name: storage-nautilus
      ports:
        - containerPort: 80
  volumes:
    - name: storage-nautilus
      persistentVolumeClaim:
        claimName: pvc-datacenter