apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-datacenter
  name: secret-datacenter
spec:
  volumes:
  - name: secret-volume-datacenter
    secret:
      secretName: beta
  containers:
  - image: fedora:latest
    name: secret-container-datacenter
    command: ["bin/bash"]
    args: ["-c", "sleep 100000"]
    volumeMounts:
    - name: secret-volume-datacenter
      mountPath: "/opt/demo"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
