apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  containers:
  - name: secret-container-nautilus
    image: ubuntu:latest    
    command: ["bin/bash"]
    args: ["-c", "sleep 10000"]
    volumeMounts:
    - name: secret-volume-nautilus
      readOnly: true
      mountPath: "/opt/games"

  volumes:
  - name: secret-volume-nautilus
    secret:
      secretName: beta
