---
- name: Deploy playbook
  hosts: all
  serial: 1
  any_errors_fatal: true
  gather_facts: true
  become: true
  tasks:
    - name: create an archive on respective servers
      archive:
        path: /usr/src/dba/
        dest: /opt/dba/cluster.tar.gz
        format: gz

    - name: assign users and groups permissions respectively
      file:
        path: /opt/dba/cluster.tar.gz
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

